### ISSUE TITLE
Game crashes when pressing tab in the world selection and world creation screens

### ISSUE THREAD

**Issue by DasGerippe** [Darkere/TabInventory#1]
Im using the 1.14 version of this mod, since I'm normally playing with otehr mods. There are several menus where pressing tab results in a crash. I have bound Open/Close Inventory to Tab.

Menus where my game crashed:
- Pressing Tab in the world selection menu
- Pressing Tab in the world creation menu (only sometimes)
- Multiplayer menu

Since most other mods aren't updated to 1.15 yet, I would really appreciate it if the 1.14 version gets fixed too.

**Comment by Darkere** [comment]
Hmm, I can get it to crash on the multiplayer menu. But this seems to be a vanilla issue. It also happens in my vanilla instance. 

I can't get it to crash on world selection or world creation. Can you post the crash report for that?

https://bugs.mojang.com/browse/MC-166684 Found the vanilla bug report

EDIT: Forgot to actually set tab as inventory. Now the crash is on me :)

**Comment by Darkere** [comment]
Should be fixed in version 1.1. Feel free to yell at me if it isn't :D

**Comment by DasGerippe** [comment]
Thanks a lot for the fast fix! :)
